/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedScribeRouteImport } from './routes/(protected)/scribe'
import { Route as protectedPatientsIndexRouteImport } from './routes/(protected)/patients.index'
import { Route as protectedChatsIndexRouteImport } from './routes/(protected)/chats.index'
import { Route as protectedChatsIdRouteImport } from './routes/(protected)/chats.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedScribeRoute = protectedScribeRouteImport.update({
  id: '/(protected)/scribe',
  path: '/scribe',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedPatientsIndexRoute = protectedPatientsIndexRouteImport.update({
  id: '/(protected)/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedChatsIndexRoute = protectedChatsIndexRouteImport.update({
  id: '/(protected)/chats/',
  path: '/chats/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedChatsIdRoute = protectedChatsIdRouteImport.update({
  id: '/(protected)/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/scribe': typeof protectedScribeRoute
  '/chats/$id': typeof protectedChatsIdRoute
  '/chats/': typeof protectedChatsIndexRoute
  '/patients/': typeof protectedPatientsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/scribe': typeof protectedScribeRoute
  '/chats/$id': typeof protectedChatsIdRoute
  '/chats': typeof protectedChatsIndexRoute
  '/patients': typeof protectedPatientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)/scribe': typeof protectedScribeRoute
  '/(protected)/chats/$id': typeof protectedChatsIdRoute
  '/(protected)/chats/': typeof protectedChatsIndexRoute
  '/(protected)/patients/': typeof protectedPatientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/scribe' | '/chats/$id' | '/chats/' | '/patients/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/scribe' | '/chats/$id' | '/chats' | '/patients'
  id:
    | '__root__'
    | '/'
    | '/(protected)/scribe'
    | '/(protected)/chats/$id'
    | '/(protected)/chats/'
    | '/(protected)/patients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedScribeRoute: typeof protectedScribeRoute
  protectedChatsIdRoute: typeof protectedChatsIdRoute
  protectedChatsIndexRoute: typeof protectedChatsIndexRoute
  protectedPatientsIndexRoute: typeof protectedPatientsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/scribe': {
      id: '/(protected)/scribe'
      path: '/scribe'
      fullPath: '/scribe'
      preLoaderRoute: typeof protectedScribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/patients/': {
      id: '/(protected)/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof protectedPatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/chats/': {
      id: '/(protected)/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof protectedChatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/chats/$id': {
      id: '/(protected)/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof protectedChatsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedScribeRoute: protectedScribeRoute,
  protectedChatsIdRoute: protectedChatsIdRoute,
  protectedChatsIndexRoute: protectedChatsIndexRoute,
  protectedPatientsIndexRoute: protectedPatientsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
