/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedScribeRouteImport } from './routes/_protected/scribe'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as ProtectedTemplatesIndexRouteImport } from './routes/_protected/templates.index'
import { Route as ProtectedSettingsIndexRouteImport } from './routes/_protected/settings.index'
import { Route as ProtectedPatientsIndexRouteImport } from './routes/_protected/patients.index'
import { Route as ProtectedChatsIndexRouteImport } from './routes/_protected/chats.index'
import { Route as ProtectedChatsIdRouteImport } from './routes/_protected/chats.$id'

const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedScribeRoute = ProtectedScribeRouteImport.update({
  id: '/scribe',
  path: '/scribe',
  getParentRoute: () => ProtectedRoute,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedTemplatesIndexRoute = ProtectedTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedSettingsIndexRoute = ProtectedSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedPatientsIndexRoute = ProtectedPatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatsIndexRoute = ProtectedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedChatsIdRoute = ProtectedChatsIdRouteImport.update({
  id: '/chats/$id',
  path: '/chats/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/scribe': typeof ProtectedScribeRoute
  '/chats/$id': typeof ProtectedChatsIdRoute
  '/chats/': typeof ProtectedChatsIndexRoute
  '/patients/': typeof ProtectedPatientsIndexRoute
  '/settings/': typeof ProtectedSettingsIndexRoute
  '/templates/': typeof ProtectedTemplatesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/scribe': typeof ProtectedScribeRoute
  '/': typeof ProtectedIndexRoute
  '/chats/$id': typeof ProtectedChatsIdRoute
  '/chats': typeof ProtectedChatsIndexRoute
  '/patients': typeof ProtectedPatientsIndexRoute
  '/settings': typeof ProtectedSettingsIndexRoute
  '/templates': typeof ProtectedTemplatesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_protected/scribe': typeof ProtectedScribeRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/chats/$id': typeof ProtectedChatsIdRoute
  '/_protected/chats/': typeof ProtectedChatsIndexRoute
  '/_protected/patients/': typeof ProtectedPatientsIndexRoute
  '/_protected/settings/': typeof ProtectedSettingsIndexRoute
  '/_protected/templates/': typeof ProtectedTemplatesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/scribe'
    | '/chats/$id'
    | '/chats/'
    | '/patients/'
    | '/settings/'
    | '/templates/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/register'
    | '/scribe'
    | '/'
    | '/chats/$id'
    | '/chats'
    | '/patients'
    | '/settings'
    | '/templates'
  id:
    | '__root__'
    | '/_protected'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_protected/scribe'
    | '/_protected/'
    | '/_protected/chats/$id'
    | '/_protected/chats/'
    | '/_protected/patients/'
    | '/_protected/settings/'
    | '/_protected/templates/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/scribe': {
      id: '/_protected/scribe'
      path: '/scribe'
      fullPath: '/scribe'
      preLoaderRoute: typeof ProtectedScribeRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/templates/': {
      id: '/_protected/templates/'
      path: '/templates'
      fullPath: '/templates/'
      preLoaderRoute: typeof ProtectedTemplatesIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/settings/': {
      id: '/_protected/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof ProtectedSettingsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/patients/': {
      id: '/_protected/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof ProtectedPatientsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chats/': {
      id: '/_protected/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof ProtectedChatsIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/chats/$id': {
      id: '/_protected/chats/$id'
      path: '/chats/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof ProtectedChatsIdRouteImport
      parentRoute: typeof ProtectedRoute
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedScribeRoute: typeof ProtectedScribeRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedChatsIdRoute: typeof ProtectedChatsIdRoute
  ProtectedChatsIndexRoute: typeof ProtectedChatsIndexRoute
  ProtectedPatientsIndexRoute: typeof ProtectedPatientsIndexRoute
  ProtectedSettingsIndexRoute: typeof ProtectedSettingsIndexRoute
  ProtectedTemplatesIndexRoute: typeof ProtectedTemplatesIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedScribeRoute: ProtectedScribeRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedChatsIdRoute: ProtectedChatsIdRoute,
  ProtectedChatsIndexRoute: ProtectedChatsIndexRoute,
  ProtectedPatientsIndexRoute: ProtectedPatientsIndexRoute,
  ProtectedSettingsIndexRoute: ProtectedSettingsIndexRoute,
  ProtectedTemplatesIndexRoute: ProtectedTemplatesIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
