/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as protectedScribeRouteImport } from './routes/(protected)/scribe'
import { Route as protectedChatsRouteImport } from './routes/(protected)/chats'
import { Route as protectedChatsIdRouteImport } from './routes/(protected)/chats.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedScribeRoute = protectedScribeRouteImport.update({
  id: '/(protected)/scribe',
  path: '/scribe',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedChatsRoute = protectedChatsRouteImport.update({
  id: '/(protected)/chats',
  path: '/chats',
  getParentRoute: () => rootRouteImport,
} as any)
const protectedChatsIdRoute = protectedChatsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => protectedChatsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chats': typeof protectedChatsRouteWithChildren
  '/scribe': typeof protectedScribeRoute
  '/chats/$id': typeof protectedChatsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chats': typeof protectedChatsRouteWithChildren
  '/scribe': typeof protectedScribeRoute
  '/chats/$id': typeof protectedChatsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(protected)/chats': typeof protectedChatsRouteWithChildren
  '/(protected)/scribe': typeof protectedScribeRoute
  '/(protected)/chats/$id': typeof protectedChatsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chats' | '/scribe' | '/chats/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chats' | '/scribe' | '/chats/$id'
  id:
    | '__root__'
    | '/'
    | '/(protected)/chats'
    | '/(protected)/scribe'
    | '/(protected)/chats/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  protectedChatsRoute: typeof protectedChatsRouteWithChildren
  protectedScribeRoute: typeof protectedScribeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/scribe': {
      id: '/(protected)/scribe'
      path: '/scribe'
      fullPath: '/scribe'
      preLoaderRoute: typeof protectedScribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/chats': {
      id: '/(protected)/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof protectedChatsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(protected)/chats/$id': {
      id: '/(protected)/chats/$id'
      path: '/$id'
      fullPath: '/chats/$id'
      preLoaderRoute: typeof protectedChatsIdRouteImport
      parentRoute: typeof protectedChatsRoute
    }
  }
}

interface protectedChatsRouteChildren {
  protectedChatsIdRoute: typeof protectedChatsIdRoute
}

const protectedChatsRouteChildren: protectedChatsRouteChildren = {
  protectedChatsIdRoute: protectedChatsIdRoute,
}

const protectedChatsRouteWithChildren = protectedChatsRoute._addFileChildren(
  protectedChatsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  protectedChatsRoute: protectedChatsRouteWithChildren,
  protectedScribeRoute: protectedScribeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
